/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 aws.glb -t -o aws.tsx 
*/

import * as THREE from 'three'
// import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Curve001: THREE.Mesh
    Curve002: THREE.Mesh
    Curve006: THREE.Mesh
  }
  materials: {
    blue: THREE.MeshStandardMaterial
    orange: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

export function Aws(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/aws.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve001.geometry} material={materials.blue} rotation={[1.363, 0, 0]} scale={55.206}>
        <mesh geometry={nodes.Curve002.geometry} material={materials.orange} />
        <mesh geometry={nodes.Curve006.geometry} material={materials.orange} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/aws.glb')
