/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf -t -o cable.tsx 
Author: Paul (https://sketchfab.com/nathan.d1563)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-pc-cable-464d4da5b46842ed8cb37b7c50168a60
Title: Low poly PC Cable
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Conection_Maps_0: THREE.Mesh
    Pc_cableMesh_Maps_0: THREE.Mesh
  }
  materials: {
    Maps: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

export function Cable(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/cable/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[1.52, 0, -3.066]}>
        <mesh geometry={nodes.Conection_Maps_0.geometry} material={materials.Maps} position={[-2.954, 2.181, 3.933]} scale={[0.092, 0.444, 0.282]} />
        <mesh geometry={nodes.Pc_cableMesh_Maps_0.geometry} material={materials.Maps} />
      </group>
    </group>
  )
}

useGLTF.preload('/cable/scene.gltf')
