/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf -t -o computer-desk.tsx 
Author: New Light (https://sketchfab.com/darthmiles24)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-computer-desk-d618d0816dec416ead339f1d8b6a97f0
Title: Stylized computer desk
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { Line, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import gsap from 'gsap'

type GLTFResult = GLTF & {
  nodes: {
    Cube_Material_0: THREE.Mesh
    Cube001_Material001_0: THREE.Mesh
    Plane_Material002_0: THREE.Mesh
    Plane001_Material019_0: THREE.Mesh
    Plane001_Material018_0: THREE.Mesh
    Cube003_Material007_0: THREE.Mesh
    Cube003_Material008_0: THREE.Mesh
    Plane003_Material005_0: THREE.Mesh
    Plane003_Material004_0: THREE.Mesh
    Cube005_Material004_0: THREE.Mesh
    Plane002_Material002_0: THREE.Mesh
    Cylinder_Material015_0: THREE.Mesh
    Cylinder_Material016_0: THREE.Mesh
    Cylinder_Material017_0: THREE.Mesh
    Cylinder001_Material002_0: THREE.Mesh
    Cylinder001_Material003_0: THREE.Mesh
    Cylinder002_Material006_0: THREE.Mesh
    Cube006_Material020_0: THREE.Mesh
    Cube006_Material022_0: THREE.Mesh
    Cube006_Material021_0: THREE.Mesh
    Cube002_Material009_0: THREE.Mesh
    Cube002_Material008_0: THREE.Mesh
    Cube004_Material010_0: THREE.Mesh
    Cube004_Material008_0: THREE.Mesh
    Cube008_Material011_0: THREE.Mesh
    Cube008_Material008_0: THREE.Mesh
    Cube009_Material012_0: THREE.Mesh
    Cube009_Material008_0: THREE.Mesh
    Cube010_Material013_0: THREE.Mesh
    Cube010_Material008_0: THREE.Mesh
    Cube011_Material014_0: THREE.Mesh
    Cube011_Material008_0: THREE.Mesh
    Cylinder003_Material015_0: THREE.Mesh
    Cylinder003_Material016_0: THREE.Mesh
    Cylinder003_Material017_0: THREE.Mesh
    Cube007_Material020_0: THREE.Mesh
    Cube007_Material022_0: THREE.Mesh
    Cube007_Material021_0: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    ['Material.022']: THREE.MeshStandardMaterial
    ['Material.021']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function ComputerDesk(props: JSX.IntrinsicElements['group']) {

  const { nodes, materials } = useGLTF('/computer-desk/scene.gltf') as GLTFResult

  return (
    <group castShadow receiveShadow {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 47.515, -43.44]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Plane001_Material019_0.geometry} material-color={"skyblue"} material={materials['Material.019']} />
          
          <mesh geometry={nodes.Plane001_Material018_0.geometry} material={materials['Material.018']} />
        </group>
        <group position={[-23.654, 41.149, -36.661]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube003_Material007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube003_Material008_0.geometry} material={materials['Material.008']} />
        </group>
        <group position={[-6.827, 40.266, -31.591]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Plane003_Material005_0.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Plane003_Material004_0.geometry} material={materials['Material.004']} />
        </group>
        <group position={[25.83, 47.738, -41.96]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cylinder_Material015_0.geometry} material={materials['Material.015']} />
          <mesh geometry={nodes.Cylinder_Material016_0.geometry} material={materials['Material.016']} />
          <mesh geometry={nodes.Cylinder_Material017_0.geometry} material={materials['Material.017']} />
        </group>
        <group position={[16.844, 45.448, -43.05]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube006_Material020_0.geometry} material={materials['Material.020']} />
          <mesh geometry={nodes.Cube006_Material022_0.geometry} material={materials['Material.022']} />
          <mesh geometry={nodes.Cube006_Material021_0.geometry} material={materials['Material.021']} />
        </group>
        <group position={[-23.553, 43.307, -36.143]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube002_Material009_0.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Cube002_Material008_0.geometry} material={materials['Material.008']} />
        </group>
        <group position={[24.879, 40.685, -30.24]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube004_Material010_0.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Cube004_Material008_0.geometry} material={materials['Material.008']} />
        </group>
        <group position={[3.748, 71.684, -40.243]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube008_Material011_0.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes.Cube008_Material008_0.geometry} material={materials['Material.008']} />
        </group>
        <group position={[3.633, 73.054, -40.233]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube009_Material012_0.geometry} material={materials['Material.012']} />
          <mesh geometry={nodes.Cube009_Material008_0.geometry} material={materials['Material.008']} />
        </group>
        <group position={[3.764, 74.723, -40.69]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube010_Material013_0.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes.Cube010_Material008_0.geometry} material={materials['Material.008']} />
        </group>
        <group position={[11.503, 71.684, -42.42]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube011_Material014_0.geometry} material={materials['Material.014']} />
          <mesh geometry={nodes.Cube011_Material008_0.geometry} material={materials['Material.008']} />
        </group>
        <group position={[-8.273, 78.737, -43.398]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cylinder003_Material015_0.geometry} material={materials['Material.015']} />
          <mesh geometry={nodes.Cylinder003_Material016_0.geometry} material={materials['Material.016']} />
          <mesh geometry={nodes.Cylinder003_Material017_0.geometry} material={materials['Material.017']} />
        </group>
        <group position={[-16.668, 46.151, -42.982]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube007_Material020_0.geometry} material={materials['Material.020']} />
          <mesh geometry={nodes.Cube007_Material022_0.geometry} material={materials['Material.022']} />
          <mesh geometry={nodes.Cube007_Material021_0.geometry} material={materials['Material.021']} />
        </group>
        <mesh geometry={nodes.Cube_Material_0.geometry} material={materials.Material} position={[0, 5, -16.476]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube001_Material001_0.geometry}  material={materials['Material.001']} position={[0, 45, -54.222]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane_Material002_0.geometry} material={materials['Material.002']} position={[0, 28.408, -34.227]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube005_Material004_0.geometry} material={materials['Material.004']} position={[5.943, 40.261, -31.368]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane002_Material002_0.geometry} material={materials['Material.002']} position={[0, 70.227, -40.001]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cylinder002_Material006_0.geometry} material={materials['Material.006']} position={[20.507, 42.017, -29.364]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/computer-desk/scene.gltf')
