/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf -t -o floppy-disk.tsx 
Author: Kami Rapacz (https://sketchfab.com/kuroderuta)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/35-high-density-floppy-disk-free-version-daaf642dbd084517a371b3ba03453a5f
Title: 3.5" High Density Floppy Disk | FREE VERSION
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Parts'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    ['3_5_inch_Floppy_Shutter__0']: THREE.Mesh
    ['3_5_inch_Floppy_Copy_Protection_Slider__0']: THREE.Mesh
    ['3_5_inch_Floppy_Magnetic_Disk__0']: THREE.Mesh
    ['3_5_inch_Floppy__0']: THREE.Mesh
  }
  materials: {
    ['Scene_-_Root']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function FloppyDisk(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/floppy-disk/scene.gltf') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-2.173, -0.278, 0]}>
          <group name="3��-inch_Floppy_Diskfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="3_5_inch_Floppy" rotation={[Math.PI / 2, 0, 0]}>
                  <group name="3_5_inch_Floppy_Shutter" position={[-2.3, 0.165, -9.25]}>
                    <mesh name="3_5_inch_Floppy_Shutter__0" geometry={nodes['3_5_inch_Floppy_Shutter__0'].geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="3_5_inch_Floppy_Copy_Protection_Slider" position={[-4, 0.083, -0.7]}>
                    <mesh name="3_5_inch_Floppy_Copy_Protection_Slider__0" geometry={nodes['3_5_inch_Floppy_Copy_Protection_Slider__0'].geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="3_5_inch_Floppy_Magnetic_Disk" position={[0, 0.165, -4.45]}>
                    <mesh name="3_5_inch_Floppy_Magnetic_Disk__0" geometry={nodes['3_5_inch_Floppy_Magnetic_Disk__0'].geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <mesh name="3_5_inch_Floppy__0" geometry={nodes['3_5_inch_Floppy__0'].geometry} material={materials['Scene_-_Root']} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/floppy-disk/scene.gltf')
