/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 like.glb -t -o chat.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane005: THREE.Mesh
    Curve002: THREE.Mesh
  }
  materials: {
    ['Material.056']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Like(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/like.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane005.geometry} material={materials['Material.056']} position={[0.136, 0.441, 0.876]} rotation={[-0.096, 0.459, 0.214]} scale={0.89} />
      <mesh geometry={nodes.Curve002.geometry} material={nodes.Curve002.material} position={[-0.032, 1.155, 1.107]} rotation={[Math.PI / 2, 0.192, -0.468]} scale={4.231} />
    </group>
  )
}

useGLTF.preload('/like.glb')
