/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 love.glb -t -o chat.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder004: THREE.Mesh
    Cube025: THREE.Mesh
  }
  materials: {
    ['Material.065']: THREE.MeshStandardMaterial
    ['Material.062']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Love(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/love.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder004.geometry} material={materials['Material.065']} position={[0.522, -0.068, -0.001]} rotation={[-0.202, 0.526, 0.525]} scale={1.107} />
      <mesh geometry={nodes.Cube025.geometry} material={materials['Material.062']} position={[0.304, 1.106, 0.568]} rotation={[-0.202, 0.526, 0.525]} scale={[0.773, 0.68, 0.372]} />
    </group>
  )
}

useGLTF.preload('/love.glb')
