/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 mongo.glb -t -o mongo.tsx 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    back: THREE.Mesh
    LOGO: THREE.Mesh
    LOGO_1: THREE.Mesh
  }
  materials: {
    ['back.002']: THREE.MeshStandardMaterial
    ['logo.002']: THREE.MeshStandardMaterial
    logo_1: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

export function Mongo(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/mongo.glb') as GLTFResult
  return (
    <group scale={20} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.back.geometry} material={materials['back.002']} />
        <mesh geometry={nodes.LOGO.geometry} material-color="gray" material={materials['logo.002']} position={[-0.142, 0.72, 0.017]} />
        <mesh geometry={nodes.LOGO_1.geometry} material-color="green" material={materials.logo_1} position={[1.481, 0.558, 0.622]} />
      </group>
    </group>
  )
}

useGLTF.preload('/mongo.glb')
