/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 sql.glb -t -o mysql.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    back: THREE.Mesh
    LOGO: THREE.Mesh
  }
  materials: {
    ['back.001']: THREE.MeshStandardMaterial
    ['logo.001']: THREE.MeshStandardMaterial
  }
}

export function MySQL(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/sql.glb') as GLTFResult
  return (
    <group scale={20} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.back.geometry} material={materials['back.001']} />
        <mesh geometry={nodes.LOGO.geometry} material-color="lightgreen" material={materials['logo.001']} position={[-0.003, 0.376, 0.013]} />
      </group>
    </group>
  )
}

useGLTF.preload('/sql.glb')
