/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf -t -o retro-router.tsx 
Author: Dominik Biały (https://sketchfab.com/crazyyuan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/grandpas-wifi-router-free-game-ready-asset-3e2b5b7d362c4dd5bedae92de2fa548f
Title: Grandpa's Wifi Router (free game-ready asset)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    FINAL_PBR_0: THREE.Mesh
  }
  materials: {
    material: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

export function RetroRouter(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/retro-router/scene.gltf') as GLTFResult
  return (
    <group rotation={[0, Math.PI/4, 0]} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.05}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.FINAL_PBR_0.geometry} material={materials.material} position={[0.254, 3.897, 1.074]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/retro-router/scene.gltf')
