/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf -t -o retro-phone.tsx 
Author: futurepunk (https://sketchfab.com/futurepunk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-android-phone-7f658554a3854ce28cae876c2a3fafd4
Title: Retro Android Phone
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
  }
  materials: {
    material_0: THREE.MeshStandardMaterial
    Phone_body: THREE.MeshStandardMaterial
    Ariel: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    phone_Face: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    Screen: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    SVGMat: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

export function RetroPhone(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/retro-phone/scene.gltf') as GLTFResult
  return (
    <group  scale={5} position={[15,-3,0]} rotation={[0,-Math.PI/3,0]} {...props} dispose={null}>
      <group position={[0.364, 0, 0.364]} rotation={[-Math.PI / 2, 0, 1.571]} scale={0.116}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-1.318, 6.523, 0.025]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.5}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.Phone_body} />
            <mesh geometry={nodes.Object_6.geometry} material={materials.Ariel} />
            <mesh geometry={nodes.Object_7.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_8.geometry} material={materials.phone_Face} />
            <mesh geometry={nodes.Object_9.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Object_10.geometry} material={materials.Screen} />
            <mesh geometry={nodes.Object_11.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Object_12.geometry} material={materials['Material.005']} />
            <mesh geometry={nodes.Object_13.geometry} material={materials['Material.010']} />
            <mesh geometry={nodes.Object_14.geometry} material={materials['Material.006']} />
            <mesh geometry={nodes.Object_15.geometry} material={materials['Material.007']} />
            <mesh geometry={nodes.Object_16.geometry} material={materials['Material.008']} />
            <mesh geometry={nodes.Object_17.geometry} material={materials['Material.009']} />
            <mesh geometry={nodes.Object_18.geometry} material={materials.SVGMat} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/retro-phone/scene.gltf')
