/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf -t -o super-computer.tsx 
Author: sudreyskr (https://sketchfab.com/sudreyskr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/univac-computer-2a5241d9d24c4e129d6dadc0b0734006
Title: UNIVAC Computer
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Legs_Computer_Legs_material_0: THREE.Mesh;
    computer_Computer_Base_material_0: THREE.Mesh;
    handles_Computer_Handle_Material_0: THREE.Mesh;
    pCube90_Computer_Handle_Material_0: THREE.Mesh;
    pCube91_Computer_Handle_Material_0: THREE.Mesh;
    pCube92_Computer_Handle_Material_0: THREE.Mesh;
    pCube93_Computer_Handle_Material_0: THREE.Mesh;
    pCube82_Computer_Handle_Material_0: THREE.Mesh;
    keyboard_Keyboard_Material_0: THREE.Mesh;
    Dial_Computer_Dial_material_0: THREE.Mesh;
    Dial1_Computer_Dial_material_0: THREE.Mesh;
    Dial2_Computer_Dial_material_0: THREE.Mesh;
    Dial3_Computer_Dial_material_0: THREE.Mesh;
    Dial4_Computer_Dial_material_0: THREE.Mesh;
    Dial5_Computer_Dial_material_0: THREE.Mesh;
    Dial6_Computer_Dial_material_0: THREE.Mesh;
    Dial7_Computer_Dial_material_0: THREE.Mesh;
    Dial8_Computer_Dial_material_0: THREE.Mesh;
    Dial9_Computer_Dial_material_0: THREE.Mesh;
    Dial10_Computer_Dial_material_0: THREE.Mesh;
    Dial11_Computer_Dial_material_0: THREE.Mesh;
    Dial12_Computer_Dial_material_0: THREE.Mesh;
    Dial13_Computer_Dial_material_0: THREE.Mesh;
    Dial14_Computer_Dial_material_0: THREE.Mesh;
    Dial15_Computer_Dial_material_0: THREE.Mesh;
    Dial16_Computer_Dial_material_0: THREE.Mesh;
    Dial17_Computer_Dial_material_0: THREE.Mesh;
    Dial18_Computer_Dial_material_0: THREE.Mesh;
    Dial19_Computer_Dial_material_0: THREE.Mesh;
    Dial20_Computer_Dial_material_0: THREE.Mesh;
    Dial21_Computer_Dial_material_0: THREE.Mesh;
    Dial22_Computer_Dial_material_0: THREE.Mesh;
    Dial23_Computer_Dial_material_0: THREE.Mesh;
    Dial24_Computer_Dial_material_0: THREE.Mesh;
    Dial25_Computer_Dial_material_0: THREE.Mesh;
    Dial26_Computer_Dial_material_0: THREE.Mesh;
    Dial27_Computer_Dial_material_0: THREE.Mesh;
    Dial28_Computer_Dial_material_0: THREE.Mesh;
    Dial29_Computer_Dial_material_0: THREE.Mesh;
    Dial30_Computer_Dial_material_0: THREE.Mesh;
    Dial31_Computer_Dial_material_0: THREE.Mesh;
    Dial32_Computer_Dial_material_0: THREE.Mesh;
    Dial33_Computer_Dial_material_0: THREE.Mesh;
    Dial34_Computer_Dial_material_0: THREE.Mesh;
    Dial35_Computer_Dial_material_0: THREE.Mesh;
    Dial36_Computer_Dial_material_0: THREE.Mesh;
    Dial37_Computer_Dial_material_0: THREE.Mesh;
    Dial38_Computer_Dial_material_0: THREE.Mesh;
    Dial39_Computer_Dial_material_0: THREE.Mesh;
    Dial40_Computer_Dial_material_0: THREE.Mesh;
    Dial41_Computer_Dial_material_0: THREE.Mesh;
    Dial42_Computer_Dial_material_0: THREE.Mesh;
    Dial43_Computer_Dial_material_0: THREE.Mesh;
    Dial44_Computer_Dial_material_0: THREE.Mesh;
    Dial45_Computer_Dial_material_0: THREE.Mesh;
    Dial46_Computer_Dial_material_0: THREE.Mesh;
    Dial47_Computer_Dial_material_0: THREE.Mesh;
    Dial48_Computer_Dial_material_0: THREE.Mesh;
    Dial49_Computer_Dial_material_0: THREE.Mesh;
    Dial50_Computer_Dial_material_0: THREE.Mesh;
    Dial51_Computer_Dial_material_0: THREE.Mesh;
    LED8_Computer_LED_Material_0: THREE.Mesh;
    LED_LIT_Computer_LED_2_Material_0: THREE.Mesh;
    LED7_Computer_LED_Material_0: THREE.Mesh;
    LED9_Computer_LED_Material_0: THREE.Mesh;
    LED4_Computer_LED_Material_0: THREE.Mesh;
    LED5_Computer_LED_Material_0: THREE.Mesh;
    LED2_Computer_LED_Material_0: THREE.Mesh;
    LED3_Computer_LED_Material_0: THREE.Mesh;
    LED1_Computer_LED_Material_0: THREE.Mesh;
    LED_Computer_LED_Material_0: THREE.Mesh;
    LED10_Computer_LED_Material_0: THREE.Mesh;
    LED11_Computer_LED_Material_0: THREE.Mesh;
    LED_LIT1_Computer_LED_2_Material_0: THREE.Mesh;
    BigLight_Computer_BigLight_Material_0: THREE.Mesh;
    BigLight_Computer1_BigLight_Material_0: THREE.Mesh;
    BigLight_Computer2_BigLight_Material_0: THREE.Mesh;
    BigLight_Computer3_BigLight_Material_0: THREE.Mesh;
    BigLight_Computer4_BigLight_Material_0: THREE.Mesh;
    BigLight_Computer5_BigLight_Material_0: THREE.Mesh;
    BigLight_Computer6_BigLight_Material_0: THREE.Mesh;
    BigLight_Computer7_BigLight_Material_0: THREE.Mesh;
    pCube127_bigswitch_brackets_material_0: THREE.Mesh;
    pCylinder17_bigswitch_material_0: THREE.Mesh;
    pCube126_bigswitch_brackets_material_0: THREE.Mesh;
    pCube128_bigswitch_brackets_material_0: THREE.Mesh;
    pCylinder18_bigswitch_material_0: THREE.Mesh;
    pCube129_bigswitch_brackets_material_0: THREE.Mesh;
    pCube130_bigswitch_brackets_material_0: THREE.Mesh;
    pCylinder19_bigswitch_material_0: THREE.Mesh;
    pCube131_bigswitch_brackets_material_0: THREE.Mesh;
    pCylinder20_bigswitch_material_0: THREE.Mesh;
    pCube132_bigswitch_brackets_material_0: THREE.Mesh;
    pCube133_bigswitch_brackets_material_0: THREE.Mesh;
    pCylinder21_bigswitch_material_0: THREE.Mesh;
    pCube134_bigswitch_brackets_material_0: THREE.Mesh;
    pCube135_bigswitch_brackets_material_0: THREE.Mesh;
    pCube127_bigswitch_brackets_material_0_1: THREE.Mesh;
    pCylinder17_bigswitch_material_0_1: THREE.Mesh;
    pCube126_bigswitch_brackets_material_0_1: THREE.Mesh;
    pCube127_bigswitch_brackets_material_0_2: THREE.Mesh;
    pCylinder17_bigswitch_material_0_2: THREE.Mesh;
    pCube126_bigswitch_brackets_material_0_2: THREE.Mesh;
    pCube127_bigswitch_brackets_material_0_3: THREE.Mesh;
    pCylinder17_bigswitch_material_0_3: THREE.Mesh;
    pCube126_bigswitch_brackets_material_0_3: THREE.Mesh;
    pCube127_bigswitch_brackets_material_0_4: THREE.Mesh;
    pCylinder17_bigswitch_material_0_4: THREE.Mesh;
    pCube126_bigswitch_brackets_material_0_4: THREE.Mesh;
    pCube127_bigswitch_brackets_material_0_5: THREE.Mesh;
    pCylinder17_bigswitch_material_0_5: THREE.Mesh;
    pCube126_bigswitch_brackets_material_0_5: THREE.Mesh;
    pCube127_bigswitch_brackets_material_0_6: THREE.Mesh;
    pCylinder17_bigswitch_material_0_6: THREE.Mesh;
    pCube126_bigswitch_brackets_material_0_6: THREE.Mesh;
    pCube127_bigswitch_brackets_material_0_7: THREE.Mesh;
    pCylinder17_bigswitch_material_0_7: THREE.Mesh;
    pCube126_bigswitch_brackets_material_0_7: THREE.Mesh;
    pCube127_bigswitch_brackets_material_0_8: THREE.Mesh;
    pCylinder17_bigswitch_material_0_8: THREE.Mesh;
    pCube126_bigswitch_brackets_material_0_8: THREE.Mesh;
    pCube127_bigswitch_brackets_material_0_9: THREE.Mesh;
    pCylinder17_bigswitch_material_0_9: THREE.Mesh;
    pCube126_bigswitch_brackets_material_0_9: THREE.Mesh;
    pCube127_bigswitch_brackets_material_0_10: THREE.Mesh;
    pCylinder17_bigswitch_material_0_10: THREE.Mesh;
    pCube126_bigswitch_brackets_material_0_10: THREE.Mesh;
    pCube127_bigswitch_brackets_material_0_11: THREE.Mesh;
    pCylinder17_bigswitch_material_0_11: THREE.Mesh;
    pCube126_bigswitch_brackets_material_0_11: THREE.Mesh;
    pCube127_bigswitch_brackets_material_0_12: THREE.Mesh;
    pCylinder17_bigswitch_material_0_12: THREE.Mesh;
    pCube126_bigswitch_brackets_material_0_12: THREE.Mesh;
    pCube127_bigswitch_brackets_material_0_13: THREE.Mesh;
    pCylinder17_bigswitch_material_0_13: THREE.Mesh;
    pCube126_bigswitch_brackets_material_0_13: THREE.Mesh;
    pCube127_bigswitch_brackets_material_0_14: THREE.Mesh;
    pCylinder17_bigswitch_material_0_14: THREE.Mesh;
    pCube126_bigswitch_brackets_material_0_14: THREE.Mesh;
    pCube127_bigswitch_brackets_material_0_15: THREE.Mesh;
    pCylinder17_bigswitch_material_0_15: THREE.Mesh;
    pCube126_bigswitch_brackets_material_0_15: THREE.Mesh;
    pCube127_bigswitch_brackets_material_0_16: THREE.Mesh;
    pCylinder17_bigswitch_material_0_16: THREE.Mesh;
    pCube126_bigswitch_brackets_material_0_16: THREE.Mesh;
    pCube127_bigswitch_brackets_material_0_17: THREE.Mesh;
    pCylinder17_bigswitch_material_0_17: THREE.Mesh;
    pCube126_bigswitch_brackets_material_0_17: THREE.Mesh;
    pCube127_bigswitch_brackets_material_0_18: THREE.Mesh;
    pCylinder17_bigswitch_material_0_18: THREE.Mesh;
    pCube126_bigswitch_brackets_material_0_18: THREE.Mesh;
    pCube127_bigswitch_brackets_material_0_19: THREE.Mesh;
    pCylinder17_bigswitch_material_0_19: THREE.Mesh;
    pCube126_bigswitch_brackets_material_0_19: THREE.Mesh;
    Meter_panel_lambert1_0: THREE.Mesh;
  };
  materials: {
    Computer_Legs_material: THREE.MeshStandardMaterial;
    Computer_Base_material: THREE.MeshStandardMaterial;
    Computer_Handle_Material: THREE.MeshStandardMaterial;
    Keyboard_Material: THREE.MeshStandardMaterial;
    Computer_Dial_material: THREE.MeshStandardMaterial;
    Computer_LED_Material: THREE.MeshStandardMaterial;
    Computer_LED_2_Material: THREE.MeshStandardMaterial;
    BigLight_Material: THREE.MeshStandardMaterial;
    bigswitch_brackets_material: THREE.MeshStandardMaterial;
    bigswitch_material: THREE.MeshStandardMaterial;
    lambert1: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function SuperComputer(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/super-computer/scene.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[0.011, 0, -0.001]} rotation={[-Math.PI / 2, 0, 0.174]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Legs_Computer_Legs_material_0.geometry}
            material={materials.Computer_Legs_material}
            position={[0, 0.011, 0]}
          />
          <mesh
            geometry={nodes.computer_Computer_Base_material_0.geometry}
            material={materials.Computer_Base_material}
          />
          <mesh
            geometry={nodes.handles_Computer_Handle_Material_0.geometry}
            material={materials.Computer_Handle_Material}
            position={[-0.95, 0.153, 0.538]}
            rotation={[Math.PI, 0, 0]}
            scale={0.379}
          />
          <mesh
            geometry={nodes.pCube90_Computer_Handle_Material_0.geometry}
            material={materials.Computer_Handle_Material}
            position={[-0.95, -0.294, 0.538]}
            rotation={[Math.PI, 0, 0]}
            scale={0.379}
          />
          <mesh
            geometry={nodes.pCube91_Computer_Handle_Material_0.geometry}
            material={materials.Computer_Handle_Material}
            position={[0.975, -0.294, 0.538]}
            rotation={[Math.PI, 0, 0]}
            scale={0.379}
          />
          <mesh
            geometry={nodes.pCube92_Computer_Handle_Material_0.geometry}
            material={materials.Computer_Handle_Material}
            position={[0.975, -0.077, 0.538]}
            rotation={[Math.PI, 0, 0]}
            scale={0.379}
          />
          <mesh
            geometry={nodes.pCube93_Computer_Handle_Material_0.geometry}
            material={materials.Computer_Handle_Material}
            position={[0.975, 0.153, 0.538]}
            rotation={[Math.PI, 0, 0]}
            scale={0.379}
          />
          <mesh
            geometry={nodes.pCube82_Computer_Handle_Material_0.geometry}
            material={materials.Computer_Handle_Material}
            position={[-0.95, -0.077, 0.538]}
            rotation={[Math.PI, 0, 0]}
            scale={0.379}
          />
          <mesh
            geometry={nodes.keyboard_Keyboard_Material_0.geometry}
            material={materials.Keyboard_Material}
          />
          <mesh
            geometry={nodes.Dial_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[-1.001, 1, -0.128]}
            rotation={[-1.92, 1.013, Math.PI]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial1_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[-0.949, 1, -0.128]}
            rotation={[1.222, 0, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial2_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[-0.898, 1, -0.128]}
            rotation={[1.222, 0, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial3_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[-0.742, 1, -0.128]}
            rotation={[1.222, -1.218, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial4_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[-0.793, 1, -0.128]}
            rotation={[1.222, 0, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial5_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[-0.845, 1, -0.128]}
            rotation={[1.222, -0.922, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial6_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[-0.742, 0.939, -0.108]}
            rotation={[1.222, 0.184, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial7_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[-0.793, 0.939, -0.108]}
            rotation={[-1.92, -0.826, -Math.PI]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial8_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[-0.845, 0.939, -0.108]}
            rotation={[1.222, 0, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial9_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[-0.898, 0.939, -0.108]}
            rotation={[1.222, 0, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial10_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[-0.949, 0.939, -0.108]}
            rotation={[1.222, 0.334, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial11_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[-1.001, 0.939, -0.108]}
            rotation={[1.222, 0.906, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial12_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[-0.742, 0.878, -0.09]}
            rotation={[1.222, 0.522, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial13_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[-0.793, 0.878, -0.09]}
            rotation={[1.222, -1.024, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial14_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[-0.845, 0.878, -0.09]}
            rotation={[1.222, 0, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial15_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[-0.898, 0.878, -0.09]}
            rotation={[1.222, 0, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial16_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[-0.949, 0.878, -0.09]}
            rotation={[1.222, 0.774, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial17_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[-1.001, 0.878, -0.09]}
            rotation={[1.222, 0.991, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial18_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.299, 1, -0.128]}
            rotation={[1.222, 0.84, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial19_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.352, 1, -0.128]}
            rotation={[1.222, 0, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial20_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.402, 1, -0.128]}
            rotation={[1.222, 0, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial21_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.559, 1, -0.128]}
            rotation={[1.222, 0.512, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial22_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.508, 1, -0.128]}
            rotation={[1.222, -0.408, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial23_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.455, 1, -0.128]}
            rotation={[1.222, -0.705, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial24_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.559, 0.939, -0.108]}
            rotation={[1.222, 0, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial25_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.508, 0.939, -0.108]}
            rotation={[1.222, -1.013, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial26_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.455, 0.939, -0.108]}
            rotation={[1.222, 0, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial27_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.402, 0.939, -0.108]}
            rotation={[1.222, 0, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial28_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.352, 0.939, -0.108]}
            rotation={[1.222, 0, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial29_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.299, 0.939, -0.108]}
            rotation={[1.222, 0, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial30_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.559, 0.878, -0.09]}
            rotation={[1.222, -0.693, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial31_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.508, 0.878, -0.09]}
            rotation={[1.222, 0, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial32_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.455, 0.878, -0.09]}
            rotation={[1.222, 0, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial33_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.402, 0.878, -0.09]}
            rotation={[1.222, 0.502, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial34_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.352, 0.878, -0.09]}
            rotation={[1.222, 0, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial35_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.299, 0.878, -0.09]}
            rotation={[1.222, 0.353, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial36_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[-0.011, 0.878, -0.09]}
            rotation={[1.222, -0.458, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial37_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.042, 0.878, -0.09]}
            rotation={[1.222, -0.176, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial38_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.093, 0.878, -0.09]}
            rotation={[1.222, 0, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial39_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.146, 0.878, -0.09]}
            rotation={[1.222, -0.558, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial40_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.198, 0.878, -0.09]}
            rotation={[1.222, 0, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial41_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.249, 0.878, -0.09]}
            rotation={[1.222, 1.552, 0]}
            scale={[0.021, 0.04, 0.021]}
          />
          <mesh
            geometry={nodes.Dial42_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.466, -0.069, 0.014]}
          />
          <mesh
            geometry={nodes.Dial43_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.466, -0.069, 0.014]}
          />
          <mesh
            geometry={nodes.Dial44_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.466, -0.069, 0.014]}
          />
          <mesh
            geometry={nodes.Dial45_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.466, -0.069, 0.014]}
          />
          <mesh
            geometry={nodes.Dial46_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.466, -0.069, 0.014]}
          />
          <mesh
            geometry={nodes.Dial47_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.466, -0.069, 0.014]}
          />
          <mesh
            geometry={nodes.Dial48_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.466, -0.069, 0.014]}
          />
          <mesh
            geometry={nodes.Dial49_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[0.466, -0.069, 0.014]}
          />
          <mesh
            geometry={nodes.Dial50_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[-0.739, 0.613, -0.016]}
            rotation={[1.222, 0, 0]}
            scale={[0.03, 0.057, 0.03]}
          />
          <mesh
            geometry={nodes.Dial51_Computer_Dial_material_0.geometry}
            material={materials.Computer_Dial_material}
            position={[-0.739, 0.702, -0.043]}
            rotation={[1.222, 0, 0]}
            scale={[0.03, 0.057, 0.03]}
          />
          <mesh
            geometry={nodes.LED8_Computer_LED_Material_0.geometry}
            material={materials.Computer_LED_Material}
            position={[-0.697, 0.798, -0.069]}
            rotation={[1.222, 0, 0]}
            scale={[0.02, 0.004, 0.02]}
          />
          <mesh
            geometry={nodes.LED_LIT_Computer_LED_2_Material_0.geometry}
            material={materials.Computer_LED_2_Material}
            position={[-0.776, 0.798, -0.069]}
            rotation={[1.222, 0, 0]}
            scale={[0.02, 0.004, 0.02]}
          />
          <mesh
            geometry={nodes.LED7_Computer_LED_Material_0.geometry}
            material={materials.Computer_LED_Material}
            position={[-0.816, 0.798, -0.069]}
            rotation={[1.222, 0, 0]}
            scale={[0.02, 0.004, 0.02]}
          />
          <mesh
            geometry={nodes.LED9_Computer_LED_Material_0.geometry}
            material={materials.Computer_LED_Material}
            position={[-0.736, 0.798, -0.069]}
            rotation={[1.222, 0, 0]}
            scale={[0.02, 0.004, 0.02]}
          />
          <mesh
            geometry={nodes.LED4_Computer_LED_Material_0.geometry}
            material={materials.Computer_LED_Material}
            position={[-0.855, 0.798, -0.069]}
            rotation={[1.222, 0, 0]}
            scale={[0.02, 0.004, 0.02]}
          />
          <mesh
            geometry={nodes.LED5_Computer_LED_Material_0.geometry}
            material={materials.Computer_LED_Material}
            position={[-0.897, 0.798, -0.069]}
            rotation={[1.222, 0, 0]}
            scale={[0.02, 0.004, 0.02]}
          />
          <mesh
            geometry={nodes.LED2_Computer_LED_Material_0.geometry}
            material={materials.Computer_LED_Material}
            position={[-0.935, 0.798, -0.069]}
            rotation={[1.222, 0, 0]}
            scale={[0.02, 0.004, 0.02]}
          />
          <mesh
            geometry={nodes.LED3_Computer_LED_Material_0.geometry}
            material={materials.Computer_LED_Material}
            position={[-0.974, 0.798, -0.069]}
            rotation={[1.222, 0, 0]}
            scale={[0.02, 0.004, 0.02]}
          />
          <mesh
            geometry={nodes.LED1_Computer_LED_Material_0.geometry}
            material={materials.Computer_LED_Material}
            position={[-1.015, 0.798, -0.069]}
            rotation={[1.222, 0, 0]}
            scale={[0.02, 0.004, 0.02]}
          />
          <mesh
            geometry={nodes.LED_Computer_LED_Material_0.geometry}
            material={materials.Computer_LED_Material}
            position={[-1.057, 0.798, -0.069]}
            rotation={[1.222, 0, 0]}
            scale={[0.02, 0.004, 0.02]}
          />
          <mesh
            geometry={nodes.LED10_Computer_LED_Material_0.geometry}
            material={materials.Computer_LED_Material}
            position={[0.953, 0.803, -0.071]}
            rotation={[1.222, 0, 0]}
            scale={[0.02, 0.004, 0.02]}
          />
          <mesh
            geometry={nodes.LED11_Computer_LED_Material_0.geometry}
            material={materials.Computer_LED_Material}
            position={[0.914, 0.803, -0.071]}
            rotation={[1.222, 0, 0]}
            scale={[0.02, 0.004, 0.02]}
          />
          <mesh
            geometry={nodes.LED_LIT1_Computer_LED_2_Material_0.geometry}
            material={materials.Computer_LED_2_Material}
            position={[0.874, 0.803, -0.071]}
            rotation={[1.222, 0, 0]}
            scale={[0.02, 0.004, 0.02]}
          />
          <mesh
            geometry={nodes.BigLight_Computer_BigLight_Material_0.geometry}
            material={materials.BigLight_Material}
            position={[-1.018, 1.251, -0.203]}
            rotation={[1.222, 0, 0]}
            scale={[0.039, 0.008, 0.039]}
          />
          <mesh
            geometry={nodes.BigLight_Computer1_BigLight_Material_0.geometry}
            material={materials.BigLight_Material}
            position={[-0.922, 1.251, -0.203]}
            rotation={[1.222, 0, 0]}
            scale={[0.039, 0.008, 0.039]}
          />
          <mesh
            geometry={nodes.BigLight_Computer2_BigLight_Material_0.geometry}
            material={materials.BigLight_Material}
            position={[-0.823, 1.251, -0.203]}
            rotation={[1.222, 0, 0]}
            scale={[0.039, 0.008, 0.039]}
          />
          <mesh
            geometry={nodes.BigLight_Computer3_BigLight_Material_0.geometry}
            material={materials.BigLight_Material}
            position={[-1.018, 1.16, -0.178]}
            rotation={[1.222, 0, 0]}
            scale={[0.039, 0.008, 0.039]}
          />
          <mesh
            geometry={nodes.BigLight_Computer4_BigLight_Material_0.geometry}
            material={materials.BigLight_Material}
            position={[-0.922, 1.16, -0.178]}
            rotation={[1.222, 0, 0]}
            scale={[0.039, 0.008, 0.039]}
          />
          <mesh
            geometry={nodes.BigLight_Computer5_BigLight_Material_0.geometry}
            material={materials.BigLight_Material}
            position={[-0.823, 1.16, -0.178]}
            rotation={[1.222, 0, 0]}
            scale={[0.039, 0.008, 0.039]}
          />
          <mesh
            geometry={nodes.BigLight_Computer6_BigLight_Material_0.geometry}
            material={materials.BigLight_Material}
            position={[-0.722, 1.251, -0.203]}
            rotation={[1.222, 0, 0]}
            scale={[0.039, 0.008, 0.039]}
          />
          <mesh
            geometry={nodes.BigLight_Computer7_BigLight_Material_0.geometry}
            material={materials.BigLight_Material}
            position={[-0.722, 1.16, -0.178]}
            rotation={[1.222, 0, 0]}
            scale={[0.039, 0.008, 0.039]}
          />
          <group position={[-0.077, 0, 0]}>
            <mesh
              geometry={nodes.pCube127_bigswitch_brackets_material_0_1.geometry}
              material={materials.bigswitch_brackets_material}
              position={[0.505, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
            <mesh
              geometry={nodes.pCylinder17_bigswitch_material_0_1.geometry}
              material={materials.bigswitch_material}
              position={[0.485, 1.198, -0.125]}
              rotation={[0.678, 0, 0]}
              scale={0.014}
            />
            <mesh
              geometry={nodes.pCube126_bigswitch_brackets_material_0_1.geometry}
              material={materials.bigswitch_brackets_material}
              position={[0.466, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
          </group>
          <group position={[-0.151, 0, 0]}>
            <mesh
              geometry={nodes.pCube127_bigswitch_brackets_material_0_2.geometry}
              material={materials.bigswitch_brackets_material}
              position={[0.505, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
            <mesh
              geometry={nodes.pCylinder17_bigswitch_material_0_2.geometry}
              material={materials.bigswitch_material}
              position={[0.485, 1.125, -0.104]}
              rotation={[1.885, 0, 0]}
              scale={0.014}
            />
            <mesh
              geometry={nodes.pCube126_bigswitch_brackets_material_0_2.geometry}
              material={materials.bigswitch_brackets_material}
              position={[0.466, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
          </group>
          <group position={[-0.228, 0, 0]}>
            <mesh
              geometry={nodes.pCube127_bigswitch_brackets_material_0_3.geometry}
              material={materials.bigswitch_brackets_material}
              position={[0.505, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
            <mesh
              geometry={nodes.pCylinder17_bigswitch_material_0_3.geometry}
              material={materials.bigswitch_material}
              position={[0.485, 1.125, -0.104]}
              rotation={[1.885, 0, 0]}
              scale={0.014}
            />
            <mesh
              geometry={nodes.pCube126_bigswitch_brackets_material_0_3.geometry}
              material={materials.bigswitch_brackets_material}
              position={[0.466, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
          </group>
          <group position={[-0.3, 0, 0]}>
            <mesh
              geometry={nodes.pCube127_bigswitch_brackets_material_0_4.geometry}
              material={materials.bigswitch_brackets_material}
              position={[0.505, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
            <mesh
              geometry={nodes.pCylinder17_bigswitch_material_0_4.geometry}
              material={materials.bigswitch_material}
              position={[0.485, 1.125, -0.104]}
              rotation={[1.885, 0, 0]}
              scale={0.014}
            />
            <mesh
              geometry={nodes.pCube126_bigswitch_brackets_material_0_4.geometry}
              material={materials.bigswitch_brackets_material}
              position={[0.466, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
          </group>
          <group position={[-0.377, 0, 0]}>
            <mesh
              geometry={nodes.pCube127_bigswitch_brackets_material_0_5.geometry}
              material={materials.bigswitch_brackets_material}
              position={[0.505, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
            <mesh
              geometry={nodes.pCylinder17_bigswitch_material_0_5.geometry}
              material={materials.bigswitch_material}
              position={[0.485, 1.198, -0.125]}
              rotation={[0.678, 0, 0]}
              scale={0.014}
            />
            <mesh
              geometry={nodes.pCube126_bigswitch_brackets_material_0_5.geometry}
              material={materials.bigswitch_brackets_material}
              position={[0.466, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
          </group>
          <group position={[-0.449, 0, 0]}>
            <mesh
              geometry={nodes.pCube127_bigswitch_brackets_material_0_6.geometry}
              material={materials.bigswitch_brackets_material}
              position={[0.505, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
            <mesh
              geometry={nodes.pCylinder17_bigswitch_material_0_6.geometry}
              material={materials.bigswitch_material}
              position={[0.485, 1.125, -0.104]}
              rotation={[1.885, 0, 0]}
              scale={0.014}
            />
            <mesh
              geometry={nodes.pCube126_bigswitch_brackets_material_0_6.geometry}
              material={materials.bigswitch_brackets_material}
              position={[0.466, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
          </group>
          <group position={[-0.526, 0, 0]}>
            <mesh
              geometry={nodes.pCube127_bigswitch_brackets_material_0_7.geometry}
              material={materials.bigswitch_brackets_material}
              position={[0.505, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
            <mesh
              geometry={nodes.pCylinder17_bigswitch_material_0_7.geometry}
              material={materials.bigswitch_material}
              position={[0.485, 1.125, -0.104]}
              rotation={[1.892, 0, 0]}
              scale={0.014}
            />
            <mesh
              geometry={nodes.pCube126_bigswitch_brackets_material_0_7.geometry}
              material={materials.bigswitch_brackets_material}
              position={[0.466, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
          </group>
          <group position={[-0.601, 0, 0]}>
            <mesh
              geometry={nodes.pCube127_bigswitch_brackets_material_0_8.geometry}
              material={materials.bigswitch_brackets_material}
              position={[0.505, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
            <mesh
              geometry={nodes.pCylinder17_bigswitch_material_0_8.geometry}
              material={materials.bigswitch_material}
              position={[0.485, 1.198, -0.125]}
              rotation={[0.678, 0, 0]}
              scale={0.014}
            />
            <mesh
              geometry={nodes.pCube126_bigswitch_brackets_material_0_8.geometry}
              material={materials.bigswitch_brackets_material}
              position={[0.466, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
          </group>
          <group position={[-0.678, 0, 0]}>
            <mesh
              geometry={nodes.pCube127_bigswitch_brackets_material_0_9.geometry}
              material={materials.bigswitch_brackets_material}
              position={[0.505, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
            <mesh
              geometry={nodes.pCylinder17_bigswitch_material_0_9.geometry}
              material={materials.bigswitch_material}
              position={[0.485, 1.198, -0.125]}
              rotation={[0.678, 0, 0]}
              scale={0.014}
            />
            <mesh
              geometry={nodes.pCube126_bigswitch_brackets_material_0_9.geometry}
              material={materials.bigswitch_brackets_material}
              position={[0.466, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
          </group>
          <group position={[-0.752, 0, 0]}>
            <mesh
              geometry={
                nodes.pCube127_bigswitch_brackets_material_0_10.geometry
              }
              material={materials.bigswitch_brackets_material}
              position={[0.505, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
            <mesh
              geometry={nodes.pCylinder17_bigswitch_material_0_10.geometry}
              material={materials.bigswitch_material}
              position={[0.485, 1.127, -0.103]}
              rotation={[1.85, 0, 0]}
              scale={0.014}
            />
            <mesh
              geometry={
                nodes.pCube126_bigswitch_brackets_material_0_10.geometry
              }
              material={materials.bigswitch_brackets_material}
              position={[0.466, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
          </group>
          <group position={[-0.829, 0, 0]}>
            <mesh
              geometry={
                nodes.pCube127_bigswitch_brackets_material_0_11.geometry
              }
              material={materials.bigswitch_brackets_material}
              position={[0.505, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
            <mesh
              geometry={nodes.pCylinder17_bigswitch_material_0_11.geometry}
              material={materials.bigswitch_material}
              position={[0.485, 1.125, -0.104]}
              rotation={[1.887, 0, 0]}
              scale={0.014}
            />
            <mesh
              geometry={
                nodes.pCube126_bigswitch_brackets_material_0_11.geometry
              }
              material={materials.bigswitch_brackets_material}
              position={[0.466, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
          </group>
          <group position={[-0.9, 0, 0]}>
            <mesh
              geometry={
                nodes.pCube127_bigswitch_brackets_material_0_12.geometry
              }
              material={materials.bigswitch_brackets_material}
              position={[0.505, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
            <mesh
              geometry={nodes.pCylinder17_bigswitch_material_0_12.geometry}
              material={materials.bigswitch_material}
              position={[0.485, 1.198, -0.125]}
              rotation={[0.678, 0, 0]}
              scale={0.014}
            />
            <mesh
              geometry={
                nodes.pCube126_bigswitch_brackets_material_0_12.geometry
              }
              material={materials.bigswitch_brackets_material}
              position={[0.466, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
          </group>
          <group position={[-0.976, 0, 0]}>
            <mesh
              geometry={
                nodes.pCube127_bigswitch_brackets_material_0_13.geometry
              }
              material={materials.bigswitch_brackets_material}
              position={[0.505, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
            <mesh
              geometry={nodes.pCylinder17_bigswitch_material_0_13.geometry}
              material={materials.bigswitch_material}
              position={[0.485, 1.126, -0.104]}
              rotation={[1.873, 0, 0]}
              scale={0.014}
            />
            <mesh
              geometry={
                nodes.pCube126_bigswitch_brackets_material_0_13.geometry
              }
              material={materials.bigswitch_brackets_material}
              position={[0.466, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
          </group>
          <group position={[-1.351, -0.072, 0.015]}>
            <mesh
              geometry={
                nodes.pCube127_bigswitch_brackets_material_0_14.geometry
              }
              material={materials.bigswitch_brackets_material}
              position={[0.505, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
            <mesh
              geometry={nodes.pCylinder17_bigswitch_material_0_14.geometry}
              material={materials.bigswitch_material}
              position={[0.485, 1.198, -0.125]}
              rotation={[0.678, 0, 0]}
              scale={0.014}
            />
            <mesh
              geometry={
                nodes.pCube126_bigswitch_brackets_material_0_14.geometry
              }
              material={materials.bigswitch_brackets_material}
              position={[0.466, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
          </group>
          <group position={[-1.425, -0.072, 0.015]}>
            <mesh
              geometry={
                nodes.pCube127_bigswitch_brackets_material_0_15.geometry
              }
              material={materials.bigswitch_brackets_material}
              position={[0.505, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
            <mesh
              geometry={nodes.pCylinder17_bigswitch_material_0_15.geometry}
              material={materials.bigswitch_material}
              position={[0.485, 1.125, -0.104]}
              rotation={[1.885, 0, 0]}
              scale={0.014}
            />
            <mesh
              geometry={
                nodes.pCube126_bigswitch_brackets_material_0_15.geometry
              }
              material={materials.bigswitch_brackets_material}
              position={[0.466, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
          </group>
          <group position={[-1.502, -0.072, 0.015]}>
            <mesh
              geometry={
                nodes.pCube127_bigswitch_brackets_material_0_16.geometry
              }
              material={materials.bigswitch_brackets_material}
              position={[0.505, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
            <mesh
              geometry={nodes.pCylinder17_bigswitch_material_0_16.geometry}
              material={materials.bigswitch_material}
              position={[0.485, 1.125, -0.104]}
              rotation={[1.885, 0, 0]}
              scale={0.014}
            />
            <mesh
              geometry={
                nodes.pCube126_bigswitch_brackets_material_0_16.geometry
              }
              material={materials.bigswitch_brackets_material}
              position={[0.466, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
          </group>
          <group position={[-1.206, -0.072, 0.015]}>
            <mesh
              geometry={
                nodes.pCube127_bigswitch_brackets_material_0_17.geometry
              }
              material={materials.bigswitch_brackets_material}
              position={[0.505, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
            <mesh
              geometry={nodes.pCylinder17_bigswitch_material_0_17.geometry}
              material={materials.bigswitch_material}
              position={[0.485, 1.125, -0.104]}
              rotation={[1.885, 0, 0]}
              scale={0.014}
            />
            <mesh
              geometry={
                nodes.pCube126_bigswitch_brackets_material_0_17.geometry
              }
              material={materials.bigswitch_brackets_material}
              position={[0.466, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
          </group>
          <group position={[-1.283, -0.072, 0.015]}>
            <mesh
              geometry={
                nodes.pCube127_bigswitch_brackets_material_0_18.geometry
              }
              material={materials.bigswitch_brackets_material}
              position={[0.505, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
            <mesh
              geometry={nodes.pCylinder17_bigswitch_material_0_18.geometry}
              material={materials.bigswitch_material}
              position={[0.485, 1.125, -0.104]}
              rotation={[1.885, 0, 0]}
              scale={0.014}
            />
            <mesh
              geometry={
                nodes.pCube126_bigswitch_brackets_material_0_18.geometry
              }
              material={materials.bigswitch_brackets_material}
              position={[0.466, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
          </group>
          <group position={[-0.249, -0.18, 0.052]}>
            <mesh
              geometry={
                nodes.pCube127_bigswitch_brackets_material_0_19.geometry
              }
              material={materials.bigswitch_brackets_material}
              position={[0.505, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
            <mesh
              geometry={nodes.pCylinder17_bigswitch_material_0_19.geometry}
              material={materials.bigswitch_material}
              position={[0.485, 1.125, -0.104]}
              rotation={[1.885, 0, 0]}
              scale={0.014}
            />
            <mesh
              geometry={
                nodes.pCube126_bigswitch_brackets_material_0_19.geometry
              }
              material={materials.bigswitch_brackets_material}
              position={[0.466, 1.152, -0.161]}
              rotation={[1.274, 0, 0]}
              scale={[0.014, 0.04, 0.061]}
            />
          </group>
          <mesh
            geometry={nodes.pCube127_bigswitch_brackets_material_0.geometry}
            material={materials.bigswitch_brackets_material}
            position={[0.505, 1.152, -0.161]}
            rotation={[1.274, 0, 0]}
            scale={[0.014, 0.04, 0.061]}
          />
          <mesh
            geometry={nodes.pCylinder17_bigswitch_material_0.geometry}
            material={materials.bigswitch_material}
            position={[0.485, 1.198, -0.125]}
            rotation={[0.678, 0, 0]}
            scale={0.014}
          />
          <mesh
            geometry={nodes.pCube126_bigswitch_brackets_material_0.geometry}
            material={materials.bigswitch_brackets_material}
            position={[0.466, 1.152, -0.161]}
            rotation={[1.274, 0, 0]}
            scale={[0.014, 0.04, 0.061]}
          />
          <mesh
            geometry={nodes.pCube128_bigswitch_brackets_material_0.geometry}
            material={materials.bigswitch_brackets_material}
            position={[1.021, 1.152, -0.161]}
            rotation={[1.274, 0, 0]}
            scale={[0.014, 0.04, 0.061]}
          />
          <mesh
            geometry={nodes.pCylinder18_bigswitch_material_0.geometry}
            material={materials.bigswitch_material}
            position={[1.04, 1.124, -0.104]}
            rotation={[1.896, 0, 0]}
            scale={0.014}
          />
          <mesh
            geometry={nodes.pCube129_bigswitch_brackets_material_0.geometry}
            material={materials.bigswitch_brackets_material}
            position={[1.059, 1.152, -0.161]}
            rotation={[1.274, 0, 0]}
            scale={[0.014, 0.04, 0.061]}
          />
          <mesh
            geometry={nodes.pCube130_bigswitch_brackets_material_0.geometry}
            material={materials.bigswitch_brackets_material}
            position={[1.021, 0.927, -0.097]}
            rotation={[1.274, 0, 0]}
            scale={[0.014, 0.04, 0.061]}
          />
          <mesh
            geometry={nodes.pCylinder19_bigswitch_material_0.geometry}
            material={materials.bigswitch_material}
            position={[1.04, 0.97, -0.064]}
            rotation={[0.678, 0, 0]}
            scale={0.014}
          />
          <mesh
            geometry={nodes.pCube131_bigswitch_brackets_material_0.geometry}
            material={materials.bigswitch_brackets_material}
            position={[1.059, 0.927, -0.097]}
            rotation={[1.274, 0, 0]}
            scale={[0.014, 0.04, 0.061]}
          />
          <mesh
            geometry={nodes.pCylinder20_bigswitch_material_0.geometry}
            material={materials.bigswitch_material}
            position={[1.04, 0.776, -0.001]}
            rotation={[0.678, 0, 0]}
            scale={0.014}
          />
          <mesh
            geometry={nodes.pCube132_bigswitch_brackets_material_0.geometry}
            material={materials.bigswitch_brackets_material}
            position={[1.021, 0.728, -0.039]}
            rotation={[1.274, 0, 0]}
            scale={[0.014, 0.04, 0.061]}
          />
          <mesh
            geometry={nodes.pCube133_bigswitch_brackets_material_0.geometry}
            material={materials.bigswitch_brackets_material}
            position={[1.059, 0.728, -0.039]}
            rotation={[1.274, 0, 0]}
            scale={[0.014, 0.04, 0.061]}
          />
          <mesh
            geometry={nodes.pCylinder21_bigswitch_material_0.geometry}
            material={materials.bigswitch_material}
            position={[-0.663, 0.697, 0.018]}
            rotation={[1.985, 0, 0]}
            scale={0.014}
          />
          <mesh
            geometry={nodes.pCube134_bigswitch_brackets_material_0.geometry}
            material={materials.bigswitch_brackets_material}
            position={[-0.644, 0.728, -0.039]}
            rotation={[1.274, 0, 0]}
            scale={[0.014, 0.04, 0.061]}
          />
          <mesh
            geometry={nodes.pCube135_bigswitch_brackets_material_0.geometry}
            material={materials.bigswitch_brackets_material}
            position={[-0.682, 0.728, -0.039]}
            rotation={[1.274, 0, 0]}
            scale={[0.014, 0.04, 0.061]}
          />
          <mesh
            geometry={nodes.Meter_panel_lambert1_0.geometry}
            material={materials.lambert1}
            position={[0.854, 1.138, -0.166]}
            rotation={[-Math.PI / 10, 0, 0]}
            scale={[0.272, 0.304, 0.045]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/super-computer/scene.gltf");
